package pertemuan10;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import static pertemuan10.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Maria Apriliani Lanus
 * TGL 21 Juni 2025
 */
public class cullinarygo extends javax.swing.JFrame {
    DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form cullinarygo
     * @throws java.sql.SQLException
     */
    public cullinarygo() throws SQLException {
        initComponents();
        tcullinarygo.setModel(dtm);
        dtm.addColumn("id");
        dtm.addColumn("Nama");
        dtm.addColumn("kategory");
        dtm.addColumn("Harga");
        dtm.addColumn("Tempat");
        
        lsDtcullinarygo();
        fieldEnabled(false);
        tombol(false);
        cBaru.setEnabled(true);
        cTutup.setEnabled(true);
        
        
    }    
    private void fieldEnabled(boolean opsi) {
        txid.setEditable(opsi);
        txnama.setEditable(opsi);
        txkategory.setEditable(opsi);
        txharga.setEditable(opsi);
        txtempat.setEditable(opsi);

    }
    private void tombol(boolean opsi){
        cBaru.setEnabled(opsi);
        cUbah.setEnabled(opsi);
        cHapus.setEnabled(opsi);
        cTutup.setEnabled(opsi);
    }
    private void clearForm(){
        txid.setText("");
        txnama.setText("");
        txkategory.setText("");
        txharga.setText("");
        txtempat.setText("");
    }
    
        private void lsDtCullinarygo() throws SQLException{
            Connection cnn = koneksi();
            
            dtm.getDataVector().removeAllElements();
            dtm.fireTableDataChanged();
            
             if(!cnn.isClosed()){
                 PreparedStatement ps = cnn.prepareStatement("SELECT * FROM cullinarygo;");
                  ResultSet rs = ps.executeQuery();
                  while( rs.next()){
                      Object[] dta = new Object[4];
                      dta[0] = rs.getString("id");
                      dta[1] = rs.getString("Nama");
                      dta[2] = rs.getString("kategory");
                      dta[3] = rs.getString("harga");
                      dta[4] = rs.getString("Tempat");
                      
                dtm.addRow(dta);
                     
                  }
                  cnn.close();
             }
        }  
        private void storeData() throws SQLException{
            Connection cnn = koneksi();
            
            if (!cnn.isClosed()){
               PreparedStatement ps = cnn.prepareStatement("INSERT INTO cullinarygo(id,Nama,kategory,Harga,Tempat) VALUES (?,?,?,?);");
               ps.setString(1, txid.getText());
               ps.setString(2, txnama.getText());
               ps.setString(3, txkategory.getText());
               ps.setString(4, txharga.getText());
               ps.setString(5, txtempat.getText());
               ps.executeUpdate();      
                cnn.close();
            }
                }
        private void updateData()throws SQLException{
             Connection cnn = koneksi();
            if (!cnn.isClosed()){
               PreparedStatement ps = cnn.prepareStatement("UPDATE cullinarygo SET Id=?,Nama=?,Kategory=?,Harga=?,Tempat=?,WHERE Nama=?;");
               ps.setString(4, txid.getText());
               ps.setString(1, txnama.getText());
               ps.setString(2, txkategory.getText());
               ps.setString(3, txharga.getText());
               ps.setString(3, txtempat.getText());
               ps.executeUpdate();      
                cnn.close();
            }
        }
        private void destoryData()throws SQLException{
          Connection cnn = koneksi();
            if (!cnn.isClosed()){
               PreparedStatement ps = cnn.prepareStatement("DELETE FROM cullinarygo WHERE Id=?;");
               ps.setString(1, txid.getText());
               ps.executeUpdate();      
                cnn.close();   
            }
        }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txid = new javax.swing.JLabel();
        txnama = new javax.swing.JLabel();
        txkategory = new javax.swing.JLabel();
        txharga = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        txKategory = new javax.swing.JTextField();
        txHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcullinarygo = new javax.swing.JTable();
        cUbah = new javax.swing.JButton();
        cBaru = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();
        txdeskripsi = new javax.swing.JLabel();
        txDeskripsi = new javax.swing.JTextField();
        txtempat = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel1.setText("Cullanarygo");

        txid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txid.setText("id");

        txnama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txnama.setText("Nama");

        txkategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txkategory.setText("Kategory");

        txharga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txharga.setText("Harga");

        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });

        txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaActionPerformed(evt);
            }
        });

        txKategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKategoryActionPerformed(evt);
            }
        });

        txHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHargaActionPerformed(evt);
            }
        });

        tcullinarygo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tcullinarygo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcullinarygoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tcullinarygo);

        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cBaru.setText("Baru");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        txdeskripsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txdeskripsi.setText("Deskripsi");

        txtempat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtempat.setText("id Tempat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cHapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtempat)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txdeskripsi)
                                        .addComponent(txharga)
                                        .addComponent(txkategory, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txnama)
                                        .addComponent(txid)
                                        .addComponent(txID)
                                        .addComponent(txNama)
                                        .addComponent(txKategory)
                                        .addComponent(txHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                        .addComponent(txDeskripsi))))
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txnama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txkategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txKategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txharga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txdeskripsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtempat)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    private void txKategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txKategoryActionPerformed

    private void txHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHargaActionPerformed

    private void txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
     
        
        if (cUbah.getText().equals("Ubah")){
            cUbah.setText("Simpan");
            cTutup.setText("Batal");
            
            cBaru.setEnabled(false);
            cHapus.setEnabled(false);
            fieldEnabled(true);
            txID.setEditable(false);
        }else{
            
            try{
                updateData();
                lsDtcullinarygo();
                clearform();
                fieldEnabled(false);
            
            cUbah.setText("Ubah");
            cTutup.setText("Tutup");
            cBaru.setEnabled(true);
       } catch (SQLException ex) {
    Logger.getLogger(cullinarygo.class.getName()).log(Level.SEVERE, null, ex);
}
      }     
    }//GEN-LAST:event_cUbahActionPerformed
    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
       int jwb = JOptionPane.showOptionDialog(
               this,
               "Yakin akan mengahpus data "+txid.getText()+"?",
               "Konfirmasi Hapus Data",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE,
               null, null, null);
       if(jwb == JOptionPane.YES_OPTION ){
        try {
            destoryData();
            lsDtcullinarygo();
            clearForm();
            cUbah.setEnabled(false);
            cHapus.setEnabled(false);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(cullinarygo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_cHapusActionPerformed

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
        if(cTutup.getText().equals("Tutup")){
        int opsi = JOptionPane.showOptionDialog(this, "Yakin akan Menutup Form?", "Konfirmasi Tutup Form", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(opsi == JOptionPane.YES_OPTION){
           System.exit(0);
        }
    }else{
            cTutup.setText("Tutup");
            cBaru.setText("Baru");
            cUbah.setText("Ubah");
               
            fieldEnabled(false);
            
            }
    }//GEN-LAST:event_cTutupActionPerformed

    private void tcullinarygoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcullinarygoMouseClicked
        txid.setText(tcullinarygo.getValueAt(tcullinarygo.getSelectedRow(), 1).toString() );
        txnama.setText(tcullinarygo.getValueAt(tcullinarygo.getSelectedRow(), 0).toString() );
        String jkx =(tcullinarygo.getValueAt(tcullinarygo.getSelectedRow(), 2).toString().equals("L"))?"Laki-Laki":"Perempuan";
        txkategory.setText(jkx);
        txharga.setText(tcullinarygo.getValueAt(tcullinarygo.getSelectedRow(), 3).toString() );
        cUbah.setEnabled(true);
        cHapus.setEnabled(true);
    }//GEN-LAST:event_tcullinarygoMouseClicked

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed
       if (cBaru.getText().equals("Baru")){
           cBaru.setText("Simpan");
           cTutup.setText("Batal");
           cUbah.setEnabled(false);
           cHapus.setEnabled(false); 
           clearForm();
           fieldEnabled(true);
       }else{
           if(!txid.getText().equals("")){
               try {   
                   storeData();
                   lsDtcullinarygo();
               } catch (SQLException ex) {
                   java.util.logging.Logger.getLogger(cullinarygo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
               }
           }
        cBaru.setText("Baru");
        cTutup.setText("Tutup");
         clearForm();
           fieldEnabled(false);
    }//GEN-LAST:event_cBaruActionPerformed
    }
    /**
     * @param args the command line arguments
     */
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cullinarygo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cullinarygo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cullinarygo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cullinarygo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new cullinarygo().setVisible(true);
                } catch (SQLException ex) {
                    //ogger.getLogger(cullinarygo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tcullinarygo;
    private javax.swing.JTextField txDeskripsi;
    private javax.swing.JTextField txHarga;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txKategory;
    private javax.swing.JTextField txNama;
    private javax.swing.JLabel txdeskripsi;
    private javax.swing.JLabel txharga;
    private javax.swing.JLabel txid;
    private javax.swing.JLabel txkategory;
    private javax.swing.JLabel txnama;
    private javax.swing.JLabel txtempat;
    // End of variables declaration//GEN-END:variables

 

  
  

   
    

}